version: '3'
services:
  gitlab:
    image: 'gitlab/gitlab-ee:latest'
    
    # コンテナが停止した際に自動で再起動する設定
    restart: always
    
    # GitLabの環境変数の設定
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        
        # GitLabの外部アクセスURLを設定
        external_url 'http://gitlab.example.com'
        
        # Nginxのリッスンポートを443 (HTTPS) に設定
        nginx['listen_port'] = 443
        
        # GitLab内部のタイムゾーンを設定
        gitlab_rails['time_zone'] = 'Asia/Tokyo'

        # メール設定
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "email-smtp.region-1.amazonaws.com"
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_user_name'] = "IAMmailerKey"
        gitlab_rails['smtp_password'] = "IAMmailerSecret"
        gitlab_rails['smtp_domain'] = "yourdomain.com"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true

        # SSL設定
        nginx['enable'] = true
        nginx['redirect_http_to_https'] = true
        nginx['ssl_certificate'] = "/etc/ssl/certs/gitlab/gitlab.example.com.crt"
        nginx['ssl_certificate_key'] = "/etc/ssl/certs/gitlab/gitlab.example.com.key"
        
        # Let's Encryptを使用しない設定
        letsencrypt['enable'] = false

        # バックアップ関連の設定
        gitlab_rails['backup_path'] = "/var/opt/gitlab/backups"
        # バックアップの保持期間を7日間に設定
        gitlab_rails['backup_keep_time'] = 604800 # 7days

    # ホストのポート443をコンテナのポート443にマッピング
    ports:
      - '443:443'

    # ホストとコンテナ間でのボリュームマッピング
    volumes:
      - '/srv/gitlab/config:/etc/gitlab' # 設定
      - '/srv/gitlab/logs:/var/log/gitlab' # ログ
      - '/srv/gitlab/data:/var/opt/gitlab' # データ
      - '/etc/ssl/certs/gitlab:/etc/ssl/certs/gitlab' # SSL証明書
      - '/srv/gitlab/backups:/var/opt/gitlab/backups' # バックアップ

    # GitLabのパフォーマンス向上のための共有メモリサイズの指定
    shm_size: '256m'
